Repository bancorprotocol/fastlane-bot, pull requests merged in 2023-09, with the labels that each got.

#105 block number fix in bot.py _get_deadline function
  fastlane_bot/bot.py
Labels: bug

#97 Balancer Flashloans now supported & used automatically when needed
  fastlane_bot/bot.py
  fastlane_bot/config/network.py
  fastlane_bot/helpers/routehandler.py
  fastlane_bot/helpers/submithandler.py
  fastlane_bot/helpers/txhelpers.py
  resources/NBTest/NBTest_051_BalancerFlashloans.ipynb
  resources/NBTest/NBTest_051_BalancerFlashloans.py
Labels: enhancement

#108 move strategy deleted event to be with other Carbon events
  fastlane_bot/events/managers/manager.py
Labels: bug

#111 110 bancor v2 bug when exchange not included or address not found
  fastlane_bot/config/logger.py
  fastlane_bot/config/selectors.py
  fastlane_bot/events/managers/base.py
  fastlane_bot/events/managers/manager.py
  fastlane_bot/events/managers/pools.py
  fastlane_bot/events/pools/bancor_v2.py
  fastlane_bot/events/pools/bancor_v3.py
  fastlane_bot/events/pools/base.py
  fastlane_bot/events/pools/carbon_v1.py
  fastlane_bot/events/pools/sushiswap_v2.py
  fastlane_bot/events/pools/uniswap_v2.py
  fastlane_bot/events/pools/uniswap_v3.py
  fastlane_bot/events/utils.py
  main.py
Labels: bug

#120 Fix for strategy deleted event
  fastlane_bot/events/exchanges/carbon_v1.py
Labels: bug

#123 115 add support for automatic pool shutdown
  fastlane_bot/config/network.py
  fastlane_bot/data/abi.py
  fastlane_bot/tools/pool_shutdown.py
  main.py
  resources/NBTest/NBTest_054_TestAutoPoolShutdown.ipynb
  resources/NBTest/NBTest_054_TestAutoPoolShutdown.py
  run_pool_shutdown.py
Labels: enhancement

#122 Add a function that changes sourceAmount to 0 for the last trade per TKN
  fastlane_bot/bot.py
  fastlane_bot/helpers/routehandler.py
  resources/NBTest/NBTest_053_TknMaxTrade.ipynb
  resources/NBTest/NBTest_053_TknMaxTrade.py
Labels: enhancement

#127 Bugfix for python 3.8 type-hints
  fastlane_bot/helpers/routehandler.py
Labels: bug

#129 Update tests to run python 3.8
  .github/workflows/run-pytest.yml
Labels: enhancement

#131 Fixed a division by zero bug.
  fastlane_bot/helpers/routehandler.py
Labels: bug

#143 bugfix for b2 key value
  fastlane_bot/events/managers/pools.py
Labels: bug

#141 Update uniswap_v2_event_mappings.csv
  fastlane_bot/data/uniswap_v2_event_mappings.csv
Labels: dependencies

#148 bugfix for POL on mainnet
  fastlane_bot/events/managers/contracts.py
  fastlane_bot/events/managers/manager.py
  fastlane_bot/events/managers/pools.py
  fastlane_bot/events/pools/bancor_pol.py
  fastlane_bot/events/pools/bancor_v2.py
  fastlane_bot/events/pools/bancor_v3.py
  fastlane_bot/events/pools/base.py
  fastlane_bot/events/pools/carbon_v1.py
  fastlane_bot/events/pools/sushiswap_v2.py
  fastlane_bot/events/pools/uniswap_v2.py
  fastlane_bot/events/pools/uniswap_v3.py
  fastlane_bot/events/utils.py
  main.py
Labels: bug

#150 Update BANCOR_POL_START_BLOCK to correct value
  fastlane_bot/config/network.py
Labels: bug

#154 Remove Tenderly Web3 instantiation
  fastlane_bot/events/managers/contracts.py
Labels: bug
