Repository bancorprotocol/fastlane-bot, pull requests merged in 2023-11, with the labels that each got.

#191 Fix router address for Uni V3
  fastlane_bot/data/multichain_addresses.csv
Labels: bug

#197 196 tokens with shutdown pools should be flashloaned from balancer
  fastlane_bot/data/blockchain_data/ethereum/static_pool_data.csv
  fastlane_bot/helpers/routehandler.py
  resources/NBTest/NBTest_051_BalancerFlashloans.ipynb
  resources/NBTest/NBTest_051_BalancerFlashloans.py
Labels: enhancement

#193 Bugfix in auto pool shutdown
  fastlane_bot/tools/pool_shutdown.py
  run_pool_shutdown.py
Labels: bug

#189 removing incompatible type reference for upcoming web3.py version change
  fastlane_bot/helpers/submithandler.py
Labels: dependencies

#202 Fix to use wei format for generating flashloans to avoid precision or rounding errors
  fastlane_bot/helpers/routehandler.py
  resources/NBTest/NBTest_051_BalancerFlashloans.ipynb
  resources/NBTest/NBTest_051_BalancerFlashloans.py
Labels: bug

#199 Add addresses & handling to route through Graphene on Base
  fastlane_bot/config/network.py
  fastlane_bot/config/provider.py
  fastlane_bot/config/selectors.py
  fastlane_bot/data/multichain_addresses.csv
  fastlane_bot/helpers/routehandler.py
  main.py
Labels: enhancement

#205 204 add prefix option to file paths which are written for deployment job write permissions
  fastlane_bot/data/blockchain_data/ethereum/tokens.csv
  fastlane_bot/events/managers/base.py
  fastlane_bot/events/managers/contracts.py
  fastlane_bot/events/utils.py
  main.py
Labels: enhancement

#211 Convert tkn key when WETH > ETH for single-flashloan creation
  fastlane_bot/helpers/routehandler.py
Labels: bug

#216 adds handling for decimals of None type
  fastlane_bot/events/interface.py
Labels: bug

#218 Create scan_log_errors.py
  scan_log_errors.py
Labels: bug

#221 bugfix strategy error
  fastlane_bot/events/pools/carbon_v1.py
Labels: bug

#224 Add standalone try except for Access List and improve error logging
  fastlane_bot/helpers/txhelpers.py
Labels: bug

#232 If gas tkn or wrapped gas token is in flashloan tokens, always include both in token list
  fastlane_bot/config/network.py
  fastlane_bot/events/interface.py
  fastlane_bot/events/utils.py
  main.py
  resources/NBTest/NBTest_034_Interface.ipynb
  resources/NBTest/NBTest_034_Interface.py
Labels: bug

#234 Update README.md
  README.md
Labels: documentation

#236 add float wrapper incase decimal input is string
  fastlane_bot/events/managers/base.py
  fastlane_bot/events/managers/contracts.py
Labels: bug

#237 Major Update - handles upcoming changes to the Fast Lane smart contract
  fastlane_bot/bot.py
  fastlane_bot/config/connect.py
  fastlane_bot/config/multicaller.py
  fastlane_bot/config/multiprovider.py
  fastlane_bot/config/network.py
  fastlane_bot/config/provider.py
  fastlane_bot/data/abi.py
  fastlane_bot/data/blockchain_data/ethereum/static_pool_data.csv
  fastlane_bot/data/blockchain_data/ethereum/tokens.csv
  fastlane_bot/events/exchanges/bancor_pol.py
  fastlane_bot/events/multicall_utils.py
  fastlane_bot/events/pools/bancor_pol.py
  fastlane_bot/events/pools/carbon_v1.py
  fastlane_bot/helpers/poolandtokens.py
  fastlane_bot/helpers/routehandler.py
  fastlane_bot/helpers/tradeinstruction.py
  fastlane_bot/helpers/txhelpers.py
  fastlane_bot/modes/pairwise_multi_pol.py
  fastlane_bot/modes/triangle_multi.py
  fastlane_bot/tools/cpc.py
  fastlane_bot/tools/optimizer/base.py
  fastlane_bot/tools/optimizer/pairoptimizer.py
  main.py
  resources/NBTest/NBTest_061_TestWETHConversion.ipynb
  resources/NBTest/NBTest_061_TestWETHConversion.py
Labels: enhancement
