Repository bancorprotocol/fastlane-bot, pull requests merged in 2023-08, with the labels that each got.

#54 Change automation to increment patch version instead of minor.
  .github/workflows/release-and-pypi-publish.yml
Labels: enhancement

#52 Adds additional installation instructions for apple-silicon users.
  README.md
Labels: documentation

#51 Creates a bash install script to handle the conda vs pip installation…
  apple-silicon-install.sh
  resources/NBTest/NBTest_902_ValidatorSlow.ipynb
  resources/NBTest/NBTest_902_ValidatorSlow.py
Labels: dependencies

#58 Fix to ensure the @click flag for flashloan_tokens is respected
  main.py
  resources/NBTest/NBTest_048_RespectFlashloanTokensClickParam.ipynb
  resources/NBTest/NBTest_048_RespectFlashloanTokensClickParam.py
  resources/NBTest/NBTest_902_ValidatorSlow.py
Labels: bug

#63 62 add target tokens setting to narrow search space
  fastlane_bot/events/interface.py
  main.py
  resources/NBTest/NBTest_902_ValidatorSlow.ipynb
  resources/NBTest/NBTest_902_ValidatorSlow.py
  resources/NBTest/NBTest_906_TargetTokens.ipynb
  resources/NBTest/NBTest_906_TargetTokens.py
Labels: enhancement

#67 Update release-and-pypi-publish.yml
  .github/workflows/release-and-pypi-publish.yml
Labels: bug

#79 Remove DAI from default `flashloan_tokens` to fix logging error message.
  main.py
Labels: bug

#84 Adds support for custom fee contract changes
  fastlane_bot/data/abi.py
  fastlane_bot/data/event_test_data.json
  fastlane_bot/events/exchanges/carbon_v1.py
  fastlane_bot/events/managers/base.py
  fastlane_bot/events/managers/events.py
  fastlane_bot/events/managers/manager.py
  fastlane_bot/events/pools/carbon_v1.py
  main.py
  resources/NBTest/NBTest_037_Exchanges.ipynb
  resources/NBTest/NBTest_037_Exchanges.py
  resources/NBTest/NBTest_049_CustomTradingFees.ipynb
  resources/NBTest/NBTest_049_CustomTradingFees.py
Labels: enhancement

#86 85 cleanup mainpy for improved logical clarity of steps
  fastlane_bot/events/utils.py
  main.py
Labels: enhancement

#90 fix issue in which validator test could randomly fail
  fastlane_bot/bot.py
  resources/NBTest/NBTest_045_Validator.ipynb
  resources/NBTest/NBTest_045_Validator.py
Labels: bug

#93 Add jupytext dependency for automated test script
  .github/workflows/run-pytest.yml
Labels: bug

#94 Adds complete runtime configuration to startup logs. Adds logging to …
  main.py
Labels: enhancement

#96 61 implement replay mode
  fastlane_bot/bot.py
  fastlane_bot/config/brownie_setup_tenderly.py
  fastlane_bot/config/network.py
  fastlane_bot/events/exchanges/carbon_v1.py
  fastlane_bot/events/interface.py
  fastlane_bot/events/managers/base.py
  fastlane_bot/events/managers/manager.py
  fastlane_bot/events/managers/pools.py
  fastlane_bot/events/utils.py
  fastlane_bot/helpers/submithandler.py
  main.py
  resources/NBTest/NBTest_043_TestEmptyCarbonOrders.ipynb
  resources/NBTest/NBTest_043_TestEmptyCarbonOrders.py
  resources/NBTest/NBTest_050_TestBancorV2.ipynb
  resources/NBTest/NBTest_050_TestBancorV2.py
Labels: enhancement

#95 Adds advanced logging infrastructure for multiple bot instance loggin…
  .gitignore
  fastlane_bot/bot.py
  fastlane_bot/config/config.py
  fastlane_bot/config/logger.py
  fastlane_bot/events/utils.py
  fastlane_bot/utils.py
  main.py
Labels: enhancement
